/* eslint-disable */
/* biome-ignore-all lint/suspicious/noExplicitAny: generated by Convex */
/* biome-ignore-all lint/complexity/noBannedTypes: generated by Convex */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import type * as common from "../common.js";
import type * as inspect from "../inspect.js";
import type * as intake from "../intake.js";
import type * as logging from "../logging.js";
import type * as queue from "../queue.js";
import type * as records from "../records.js";
import type * as threads from "../threads.js";
import type * as view from "../view.js";
import type * as work from "../work.js";

declare const fullApi: ApiFromModules<{
  common: typeof common;
  inspect: typeof inspect;
  intake: typeof intake;
  logging: typeof logging;
  queue: typeof queue;
  records: typeof records;
  threads: typeof threads;
  view: typeof view;
  work: typeof work;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;

export declare const components: {};
