import { randomBytes } from "node:crypto";
import { rmSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import { fireThreadTouch } from "../../shared-tech/context.js";
import { type ErrorResult, type OpResult, storageFailure } from "../../shared-tech/errors.js";
import {
  CURRENT_THREAD_SCHEMA_VERSION,
  getSchemaVersion,
  openDatabase,
  SQLITE_BUSY_TIMEOUT_MS,
} from "../../shared-tech/storage.js";
import {
  derivationLogSchemaStatements,
  isSupportedThreadSchemaVersion,
  migrateThreadSchema,
  retrievalImpressionSchemaStatements,
  THREAD_SCHEMA_VERSION_1,
} from "../../shared-tech/thread-migrate.js";
import { TOKEN_ESTIMATOR_ID } from "../../shared-tech/token-counting/index.js";

// The one random id: its uniqueness scope is global across files and
// registries (design decision 7).
export function generateThreadId(): string {
  return `th_${randomBytes(8).toString("hex")}`;
}

function threadSchemaStatements(threadId: string, createdAt: string): string[] {
  // Interpolated values are generated by this module (hex id, ISO timestamp,
  // estimator constant), not caller input.
  return [
    `CREATE TABLE thread_metadata (
      id INTEGER PRIMARY KEY CHECK (id = 1),
      thread_id TEXT NOT NULL,
      created_at TEXT NOT NULL,
      token_estimator TEXT NOT NULL
    );`,
    `INSERT INTO thread_metadata (id, thread_id, created_at, token_estimator)
     VALUES (1, '${threadId}', '${createdAt}', '${TOKEN_ESTIMATOR_ID}');`,
    `CREATE TABLE event (
      event_order INTEGER PRIMARY KEY,
      event_kind TEXT NOT NULL,
      idempotency_key TEXT NOT NULL UNIQUE,
      actor TEXT NOT NULL,
      harness TEXT NOT NULL,
      payload TEXT NOT NULL,
      recorded_at TEXT NOT NULL
    );`,
    `CREATE TABLE turns (
      turn_id TEXT PRIMARY KEY,
      turn_order INTEGER NOT NULL UNIQUE,
      status TEXT NOT NULL CHECK (status IN ('open', 'closed')),
      opened_at_event_order INTEGER NOT NULL,
      closed_at_event_order INTEGER,
      outcome TEXT CHECK (outcome IN ('completed', 'aborted') OR outcome IS NULL),
      outcome_reason TEXT,
      started_at TEXT,
      ended_at TEXT,
      deleted_at TEXT
    );`,
    `CREATE TABLE message (
      message_id TEXT PRIMARY KEY,
      source_event_order INTEGER NOT NULL UNIQUE REFERENCES event(event_order),
      kind TEXT NOT NULL,
      token_estimate INTEGER NOT NULL,
      actor TEXT NOT NULL,
      harness TEXT NOT NULL,
      turn_id TEXT NOT NULL REFERENCES turns(turn_id),
      provider_usage TEXT,
      deleted_at TEXT
    );`,
    `CREATE TABLE message_block (
      message_id TEXT NOT NULL REFERENCES message(message_id),
      block_index INTEGER NOT NULL,
      block_type TEXT NOT NULL,
      content TEXT NOT NULL,
      PRIMARY KEY (message_id, block_index)
    );`,
    `CREATE TABLE work_item (
      work_item_id TEXT PRIMARY KEY,
      owner TEXT NOT NULL,
      kind TEXT NOT NULL,
      source_ref TEXT NOT NULL,
      status TEXT NOT NULL,
      queued_at TEXT NOT NULL,
      claimed_at TEXT,
      claim_expires_at TEXT,
      payload TEXT NOT NULL
    );`,
    `CREATE INDEX idx_work_item_queue ON work_item (status);`,
    `CREATE INDEX idx_message_block_tool_call_id
       ON message_block (block_type, json_extract(content, '$.toolCallId'));`,
    `CREATE TABLE derivation (
      subject_kind TEXT NOT NULL CHECK (subject_kind IN ('message','turn','chunk')),
      subject_id TEXT NOT NULL,
      derivation_type TEXT NOT NULL,
      state TEXT NOT NULL CHECK (state IN ('pending','ready','failed','blocked')),
      content TEXT,
      reason TEXT,
      metadata TEXT,
      source_version INTEGER NOT NULL DEFAULT 1,
      gaps TEXT,
      derived_at TEXT,
      PRIMARY KEY (subject_kind, subject_id, derivation_type)
    );`,
    `CREATE TABLE chunk (
      chunk_id TEXT PRIMARY KEY,
      chunk_order INTEGER NOT NULL UNIQUE,
      status TEXT NOT NULL CHECK (status IN ('open','closed')),
      accumulated_projected_tokens INTEGER NOT NULL DEFAULT 0
    );`,
    `CREATE TABLE chunk_member (
      chunk_id TEXT NOT NULL REFERENCES chunk(chunk_id),
      turn_id TEXT NOT NULL UNIQUE REFERENCES turns(turn_id),
      member_idx INTEGER NOT NULL,
      PRIMARY KEY (chunk_id, member_idx)
    );`,
    `CREATE TABLE thread_view (
      singleton INTEGER PRIMARY KEY CHECK (singleton = 1),
      view_id TEXT NOT NULL UNIQUE,
      created_at TEXT NOT NULL,
      compact_point INTEGER NOT NULL,
      covered_from INTEGER NOT NULL,
      profile_name TEXT,
      config_json TEXT NOT NULL,
      arrangement_json TEXT NOT NULL,
      gaps_json TEXT NOT NULL,
      source_state_json TEXT NOT NULL
    );`,
    `CREATE TABLE thread_view_band (
      view_id TEXT NOT NULL REFERENCES thread_view(view_id) ON DELETE CASCADE,
      band TEXT NOT NULL CHECK (band IN ('brief','detailed','smooth')),
      rendered_text TEXT NOT NULL,
      token_count INTEGER NOT NULL,
      PRIMARY KEY (view_id, band)
    );`,
    `CREATE TABLE view_boundary (
      thread_singleton INTEGER PRIMARY KEY CHECK (thread_singleton = 1),
      position INTEGER NOT NULL,
      updated_at TEXT NOT NULL
    );`,
    `INSERT INTO view_boundary (thread_singleton, position, updated_at)
      VALUES (1, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));`,
    `CREATE TABLE log (
      log_id INTEGER PRIMARY KEY AUTOINCREMENT,
      level TEXT NOT NULL CHECK (level IN ('info','warning','error')),
      message TEXT NOT NULL,
      derivation_type TEXT,
      subject_id TEXT,
      reason TEXT,
      floor_used TEXT,
      recorded_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
    );`,
    `CREATE INDEX idx_log_level ON log (level);`,
    `CREATE INDEX idx_log_derivation_type ON log (derivation_type);`,
    `CREATE INDEX idx_log_subject_id ON log (subject_id);`,
    `CREATE INDEX idx_log_reason ON log (reason);`,
    ...derivationLogSchemaStatements(),
    ...retrievalImpressionSchemaStatements(),
    `INSERT INTO turns (turn_id, turn_order, status, opened_at_event_order)
     VALUES ('t1', 1, 'open', 0);`,
    `PRAGMA user_version = ${CURRENT_THREAD_SCHEMA_VERSION};`,
  ];
}

function notAThreadFile(filePath: string, detail: string): { ok: false; error: ErrorResult } {
  return {
    ok: false,
    error: {
      errorClass: "caller_error",
      code: "thread_not_found",
      reason: `file at ${filePath} exists but is not an lhc thread file (${detail})`,
    },
  };
}

function errorDetail(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause);
}

// Identity check on a read-only handle so an invalid file cannot be mutated by
// the probe itself (F-03-002): a thread file carries the current schema marker
// and the thread_metadata singleton row that creation wrote transactionally.
// Anything else is rejected as a caller error, never adopted.
function validateThreadFile(filePath: string): { ok: true } | { ok: false; error: ErrorResult } {
  let db: DatabaseSync | undefined;
  try {
    // Must share the same busy timeout as writers: read-only probes under WAL
    // still wait briefly when a cross-process writer holds a reserved lock.
    // Default DatabaseSync timeout is 0 → instant "database is locked".
    db = new DatabaseSync(filePath, { readOnly: true, timeout: SQLITE_BUSY_TIMEOUT_MS });
    try {
      db.exec(`PRAGMA busy_timeout = ${SQLITE_BUSY_TIMEOUT_MS};`);
    } catch {
      // read-only may reject some pragmas; constructor timeout still applies
    }
    const schemaVersion = getSchemaVersion(db);
    if (schemaVersion === 0) {
      return notAThreadFile(filePath, "no lhc schema version");
    }
    if (!isSupportedThreadSchemaVersion(schemaVersion)) {
      return notAThreadFile(
        filePath,
        `schema version ${schemaVersion}, expected ${THREAD_SCHEMA_VERSION_1}..${CURRENT_THREAD_SCHEMA_VERSION}`,
      );
    }
    const table = db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'thread_metadata'").get();
    if (table === undefined) {
      return notAThreadFile(filePath, "no thread_metadata table");
    }
    const row = db.prepare("SELECT thread_id FROM thread_metadata WHERE id = 1").get();
    if (row === undefined) {
      return notAThreadFile(filePath, "no thread metadata row");
    }
    return { ok: true };
  } catch (cause) {
    const detail = errorDetail(cause);
    // SQLite refusing the file as a database is an identity failure, not an
    // environment failure; everything else stays a system error.
    if (detail.includes("not a database")) {
      return notAThreadFile(filePath, detail);
    }
    return storageFailure(`could not inspect thread file: ${detail}`);
  } finally {
    db?.close();
  }
}

// Opens a current thread file. Older supported schema versions are migrated on
// open; callers pass an LHC thread file or receive a caller error.
export function openThreadDatabase(filePath: string): OpResult<DatabaseSync> {
  const valid = validateThreadFile(filePath);
  if (!valid.ok) return valid;
  let db: DatabaseSync | undefined;
  try {
    db = openDatabase(filePath);
    migrateThreadSchema(db);
  } catch (cause) {
    db?.close();
    return storageFailure(`could not open thread file: ${errorDetail(cause)}`);
  }
  // Announce the open: the background scheduler's first-touch catch-up hangs
  // off this seam. Fired before any caller transaction begins; a no-op unless a
  // listener is installed.
  fireThreadTouch(filePath, db);
  return { ok: true, value: db };
}

// The full current schema, metadata row, and initial open turn land in one
// transaction, so creation succeeds whole or fails whole.
export function createThreadFile(filePath: string, threadId: string, createdAt: string): void {
  const db = openDatabase(filePath);
  try {
    db.exec("BEGIN IMMEDIATE;");
    try {
      for (const statement of threadSchemaStatements(threadId, createdAt)) db.exec(statement);
      db.exec("COMMIT;");
    } catch (cause) {
      db.exec("ROLLBACK;");
      throw cause;
    }
  } finally {
    db.close();
  }
}

// Compensation: removes the thread file and its WAL companions. Used when the
// registry insert fails after file creation (no registry row without its
// file) and when file creation itself fails partway.
export function deleteThreadFile(filePath: string): void {
  for (const suffix of ["", "-wal", "-shm"]) {
    rmSync(`${filePath}${suffix}`, { force: true });
  }
}
