import { randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

/** pi-lhc home directory: `PI_LHC_HOME` override when set, `~/.pi-lhc` otherwise. */
export function piLhcHome(): string {
  const override = process.env.PI_LHC_HOME;
  return override !== undefined && override !== "" ? override : join(homedir(), ".pi-lhc");
}

export function defaultRegistryPath(): string {
  return join(piLhcHome(), "registry.sqlite");
}

/** Default new-thread file location: `<home>/threads/<uuid>.sqlite`. The id is
 *  generated by the registry at creation, so the file name is just a unique
 *  handle; the directory is ensured up front (DatabaseSync does not create
 *  parents). */
export function defaultNewThreadFilePath(): string {
  const dir = join(piLhcHome(), "threads");
  mkdirSync(dir, { recursive: true });
  return join(dir, `${randomUUID()}.sqlite`);
}
