import { randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";

/** pi-lhc home directory: `PI_LHC_HOME` override when set, `~/.pi-lhc` otherwise. */
export function piLhcHome(): string {
  const override = process.env.PI_LHC_HOME;
  return override !== undefined && override !== "" ? resolve(override) : join(homedir(), ".pi-lhc");
}

export function defaultRegistryPath(): string {
  return join(piLhcHome(), "registry.sqlite");
}

/** PI agent config directory under the pi-lhc home: `<home>/pi/agent`. */
export function piLhcAgentDir(): string {
  return join(piLhcHome(), "pi", "agent");
}

/**
 * Ensure `PI_CODING_AGENT_DIR` points at the pi-lhc-owned agent dir.
 * Respects a pre-set non-empty value (operator override); otherwise sets the
 * env to `piLhcAgentDir()` after creating the directory (first-run bootstrap).
 * Empty-string env is treated as unset.
 */
export function ensurePiAgentDirEnv(): string {
  const preset = process.env.PI_CODING_AGENT_DIR;
  if (preset !== undefined && preset !== "") {
    return preset;
  }
  const dir = piLhcAgentDir();
  mkdirSync(dir, { recursive: true });
  process.env.PI_CODING_AGENT_DIR = dir;
  return dir;
}

/** Default new-thread file location: `<home>/threads/<uuid>.sqlite`. The id is
 *  generated by the registry at creation, so the file name is just a unique
 *  handle; the directory is ensured up front (DatabaseSync does not create
 *  parents). */
export function defaultNewThreadFilePath(): string {
  const dir = join(piLhcHome(), "threads");
  mkdirSync(dir, { recursive: true });
  return join(dir, `${randomUUID()}.sqlite`);
}
