//! TS→Rust parity for shared_tech/content_blocks.rs against
//! fixtures/content-blocks-cases.json (generated by
//! scripts/gen-content-blocks-fixtures.mjs from the TS module itself).
//!
//! Byte-exact on the JSON.stringify of extracted and inlined blocks (key
//! order included), the blob rows, and each block's placeholder line and
//! token estimate. Rust-only (no TS twin) — the TS side is the oracle.

use lhc::shared_tech::content_blocks::{
    blob_token_estimate, extract_blobs, has_blob_payload, inline_blobs, placeholder_text,
};
use lhc::shared_tech::js_json::js_json_stringify;
use serde_json::Value;

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct BlobRow {
    sha256: String,
    media_type: Option<String>,
    byte_length: i64,
}

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct Case {
    name: String,
    input: String,
    extracted: String,
    blobs: Vec<BlobRow>,
    placeholders: Vec<String>,
    token_estimates: Vec<i64>,
    has_blob_payload: Vec<bool>,
    inlined: String,
    inlined_missing: String,
}

fn cases() -> Vec<Case> {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/content-blocks-cases.json"
    ))
    .expect("fixture present");
    serde_json::from_str(&raw).expect("fixture parses")
}

#[test]
fn content_blocks_match_the_typescript_oracle_byte_for_byte() {
    let cases = cases();
    assert!(cases.len() >= 20, "fixture has {} cases", cases.len());
    for case in cases {
        let input: Vec<Value> = serde_json::from_str(&case.input).expect("input array");
        let result = extract_blobs(&input);
        let extracted = Value::Array(result.blocks.clone());
        assert_eq!(
            js_json_stringify(&extracted),
            case.extracted,
            "{}: extracted",
            case.name
        );

        let blobs: Vec<(String, Option<String>, i64)> = result
            .blobs
            .iter()
            .map(|b| (b.sha256.clone(), b.media_type.clone(), b.data.len() as i64))
            .collect();
        let expected: Vec<(String, Option<String>, i64)> = case
            .blobs
            .iter()
            .map(|b| (b.sha256.clone(), b.media_type.clone(), b.byte_length))
            .collect();
        assert_eq!(blobs, expected, "{}: blobs", case.name);

        let placeholders: Vec<String> = result.blocks.iter().map(placeholder_text).collect();
        assert_eq!(
            placeholders, case.placeholders,
            "{}: placeholders",
            case.name
        );
        let estimates: Vec<i64> = result.blocks.iter().map(blob_token_estimate).collect();
        assert_eq!(
            estimates, case.token_estimates,
            "{}: token estimates",
            case.name
        );
        let has: Vec<bool> = result.blocks.iter().map(has_blob_payload).collect();
        assert_eq!(
            has, case.has_blob_payload,
            "{}: has_blob_payload",
            case.name
        );

        let store: Vec<(String, Vec<u8>)> = result
            .blobs
            .iter()
            .map(|b| (b.sha256.clone(), b.data.clone()))
            .collect();
        let load = |h: &str| store.iter().find(|(k, _)| k == h).map(|(_, d)| d.clone());
        assert_eq!(
            js_json_stringify(&inline_blobs(&extracted, &load)),
            case.inlined,
            "{}: inlined",
            case.name
        );
        let none = |_: &str| None;
        assert_eq!(
            js_json_stringify(&inline_blobs(&extracted, &none)),
            case.inlined_missing,
            "{}: inlined (missing blobs keep their reference)",
            case.name
        );
    }
}
