//! Turn parts — TS→Rust differential oracle (Story 4 acceptance spine).
//!
//! `fixtures/turn-parts-oracle.json` is generated by the TypeScript SDK
//! (scripts/gen-turn-parts-oracle.mjs): scripted intake, prepare → install
//! with a pinned createdAt, and the bytes each compact produced. This test
//! replays the same script through the Rust port and requires byte-identical
//! output: the receipt's placement/config projection, every rendered band,
//! the selection entries (seam lines, cap markers, prices), the persisted
//! config/arrangement/gaps JSON, the served LLM request context, and the host
//! metadata. No drain runs on either side: every construction is composed
//! from canonical in-walk.
mod fixtures;

use fixtures::turn_parts::{context, file_ref, host_metadata, new_thread, sdk_for, send};
use fixtures::{open_raw, temp_store};
use lhc::intake_stream::MessageEventInput;
use lhc::shared_tech::errors::OpResult;
use lhc::shared_tech::js_json::js_json_stringify;
use lhc::shared_tech::storage::SqlParam;
use lhc::shared_tech::view::ViewCompactParams;
use lhc::thread_view::{
    CompactOpts, InstallPreparedOptions, install_prepared_compact, prepare_compact,
};
use serde::Deserialize;
use serde_json::{Map, Value, json};

#[derive(Deserialize)]
struct Oracle {
    scenarios: Vec<Scenario>,
}

#[derive(Deserialize)]
struct Scenario {
    name: String,
    ops: Vec<Op>,
}

#[derive(Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
enum Op {
    Send {
        events: Vec<Value>,
    },
    #[serde(rename_all = "camelCase")]
    SetTokens {
        turn_id: String,
        token_estimate: i64,
        step_indexed: StepIndexed,
    },
    #[serde(rename_all = "camelCase")]
    Compact {
        params: ViewCompactParams,
        created_at: String,
        expect: Expect,
    },
}

#[derive(Clone, Copy, Deserialize)]
#[serde(rename_all = "snake_case")]
enum StepIndexed {
    Any,
    Yes,
    No,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expect {
    receipt: String,
    rendered_bands: Vec<RenderedBand>,
    entries: String,
    stored: Stored,
    served: String,
    host_metadata: String,
}

#[derive(Deserialize, Debug, PartialEq)]
struct RenderedBand {
    band: String,
    text: String,
}

#[derive(Deserialize, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
struct Stored {
    config_json: String,
    arrangement_json: String,
    gaps_json: String,
    parts_activated_at: Option<String>,
}

/// JSON.stringify over recursively key-sorted objects — the generator's
/// `canon()`; JS number/string rendering via js_json.
fn canon(value: Value) -> String {
    fn sort(value: Value) -> Value {
        match value {
            Value::Array(items) => Value::Array(items.into_iter().map(sort).collect()),
            Value::Object(map) => {
                let mut keys: Vec<String> = map.keys().cloned().collect();
                keys.sort();
                let mut sorted = Map::new();
                for key in keys {
                    let v = map.get(&key).cloned().unwrap_or(Value::Null);
                    sorted.insert(key, sort(v));
                }
                Value::Object(sorted)
            }
            other => other,
        }
    }
    js_json_stringify(&sort(value))
}

fn stored_rows(file_path: &str) -> Stored {
    let db = open_raw(file_path);
    let row = db
        .prepare(
            "SELECT config_json, arrangement_json, gaps_json FROM thread_view WHERE singleton = 1",
        )
        .get()
        .expect("installed view row");
    let meta = db
        .prepare("SELECT parts_activated_at FROM thread_metadata WHERE id = 1")
        .get()
        .expect("thread_metadata");
    db.close();
    Stored {
        config_json: row["config_json"]
            .as_str()
            .expect("config_json")
            .to_string(),
        arrangement_json: row["arrangement_json"]
            .as_str()
            .expect("arrangement_json")
            .to_string(),
        gaps_json: row["gaps_json"].as_str().expect("gaps_json").to_string(),
        parts_activated_at: meta["parts_activated_at"].as_str().map(str::to_string),
    }
}

#[tokio::test]
async fn replays_the_typescript_oracle_byte_for_byte() {
    let body = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/turn-parts-oracle.json"
    ))
    .expect("read turn-parts-oracle.json");
    let oracle: Oracle = serde_json::from_str(&body).expect("oracle json");
    assert!(!oracle.scenarios.is_empty());
    let store = temp_store();
    let sdk = sdk_for();
    let mut compacts = 0usize;
    for scenario in &oracle.scenarios {
        let file_path = new_thread(&sdk, &store).await;
        for (index, op) in scenario.ops.iter().enumerate() {
            let at = format!("{}#{index}", scenario.name);
            match op {
                Op::Send { events } => {
                    let events: Vec<MessageEventInput> = events
                        .iter()
                        .map(|e| serde_json::from_value(e.clone()).expect("fixture event"))
                        .collect();
                    send(&sdk, &file_path, &events).await;
                }
                Op::SetTokens {
                    turn_id,
                    token_estimate,
                    step_indexed,
                } => {
                    let step_predicate = match step_indexed {
                        StepIndexed::Any => "",
                        StepIndexed::Yes => " AND step_index IS NOT NULL",
                        StepIndexed::No => " AND step_index IS NULL",
                    };
                    let db = open_raw(&file_path);
                    db.prepare(&format!(
                        "UPDATE message SET token_estimate = ? WHERE turn_id = ?{step_predicate}"
                    ))
                    .run(&[
                        SqlParam::from(*token_estimate),
                        SqlParam::from(turn_id.as_str()),
                    ]);
                    db.close();
                }
                Op::Compact {
                    params,
                    created_at,
                    expect,
                } => {
                    compacts += 1;
                    let prepared = match prepare_compact(
                        file_ref(&file_path),
                        CompactOpts {
                            profile: None,
                            params: Some(params.clone()),
                            signal: None,
                            compact_point_upper_bound: None,
                        },
                    )
                    .await
                    {
                        OpResult::Ok { value } => value,
                        OpResult::Err { error } => panic!("{at}: prepare: {}", error.reason),
                    };
                    let entries: Vec<Value> = prepared
                        .selection
                        .entries
                        .iter()
                        .map(|e| {
                            let mut entry = json!({
                                "band": e.band.as_str(),
                                "subjectKind": e.subject_kind,
                                "subjectId": e.subject_id,
                                "derivationUsed": e.derivation_used,
                                "degraded": e.degraded,
                                "gap": e.gap,
                                "startOrder": e.start_order,
                                "tokens": e.tokens,
                                "text": e.text,
                            });
                            if let Some(part) = e.part {
                                entry["part"] =
                                    json!({ "fromStep": part.from_step, "toStep": part.to_step });
                            }
                            entry
                        })
                        .collect();
                    let receipt = match install_prepared_compact(
                        file_ref(&file_path),
                        prepared,
                        InstallPreparedOptions {
                            created_at: Some(created_at.clone()),
                            ..InstallPreparedOptions::default()
                        },
                    )
                    .await
                    {
                        OpResult::Ok { value } => value,
                        OpResult::Err { error } => panic!("{at}: install: {}", error.reason),
                    };
                    let projection = json!({
                        "viewId": receipt.view_id,
                        "compactPoint": receipt.compact_point,
                        "coveredFrom": receipt.covered_from,
                        "tailTokens": receipt.tail_tokens,
                        "totalTokens": receipt.total_tokens,
                        "bands": receipt.bands,
                        "config": receipt.config,
                        "parts": receipt.parts,
                        "splitPoint": receipt.split_point,
                        "settled": receipt.settled,
                        "protectedTurn": receipt.protected_turn,
                        "firstKeptMessageId": receipt.first_kept_message_id,
                    });
                    assert_eq!(
                        canon(projection),
                        expect.receipt,
                        "{at}: receipt projection"
                    );
                    let rendered: Vec<RenderedBand> = receipt
                        .rendered_bands
                        .iter()
                        .map(|b| RenderedBand {
                            band: b.band.as_str().to_string(),
                            text: b.text.clone(),
                        })
                        .collect();
                    assert_eq!(rendered, expect.rendered_bands, "{at}: rendered bands");
                    assert_eq!(
                        canon(Value::Array(entries)),
                        expect.entries,
                        "{at}: selection entries"
                    );
                    assert_eq!(stored_rows(&file_path), expect.stored, "{at}: stored rows");
                    let ctx = context(&file_path).await;
                    assert_eq!(
                        canon(serde_json::to_value(&ctx.messages).expect("json")),
                        expect.served,
                        "{at}: served context"
                    );
                    let meta = host_metadata(&file_path).await;
                    let meta_json = json!({
                        "activeTurn": meta.active_turn.as_ref().map(|a| json!({
                            "turnId": a.turn_id,
                            "estimatedTokens": a.estimated_tokens,
                            "completeSteps": a.complete_steps,
                            "lastStepEdge": a.last_step_edge,
                            "splittable": a.splittable,
                        })),
                        "unsettledTurn": meta.unsettled_turn.as_ref().map(|u| json!({ "turnId": u.turn_id })),
                    });
                    assert_eq!(
                        canon(meta_json),
                        expect.host_metadata,
                        "{at}: host metadata"
                    );
                }
            }
        }
    }
    assert_eq!(compacts, 19, "the oracle's compact count");
    store.cleanup();
}
