"""Ported from packages/lhc/src/shared-tech/index.ts.

Public technical surface for mechanism-only capabilities consumed by LHC
product domains. Sub-capabilities with their own public entrypoints
(`work-queue`, `token-counting`, `logging`, `prompts`) remain importable
directly; everything else should flow through this index.
"""

from __future__ import annotations

from .classify import (
    safe_call,
)

from .context import (
    InstanceSeam,
    fire_thread_touch,
    resolve_instance_config,
    resolve_instance_poke,
    resolve_instance_view_config,
    run_with_instance_seam,
    run_with_thread_touch_suppressed,
    set_scheduler_poke,
    set_thread_touch,
)

from .derivation import (
    INFERENCE_CALLBACK_OPERATIONS,
    CompletionTx,
    DependencyGap,
    Derivation,
    DerivationMetadata,
    DerivationReportEntry,
    DerivationState,
    HandlerDerivationWrite,
    HandlerOutcome,
    HandlerRunContext,
    InferenceCallbackName,
    InferenceCallbacks,
    InferenceRequestMessage,
    InferenceResult,
    ProviderProvenance,
    RenderingPart,
    RenderingPartKind,
    ResolvedSdkConfig,
    SdkConfig,
    SubjectKind,
    ToolOutcome,
    ToolResultClassification,
    ToolResultFacts,
    ToolResultOperationClass,
    ToolResultPromptMode,
    ToolResultResponseShape,
    WorkHandler,
)

from .deterministic import (
    DETERMINISTIC_MARKERS,
    DeterministicOpName,
    create_deterministic_inference_callbacks,
    deterministic_digest,
    deterministic_outcomes_suffix,
    deterministic_text,
)

from .durable_work import (
    DerivationAttempt,
    DerivationCompletionError,
    DurableWorkDispatcher,
    DurableWorkDispatcherMap,
    DurableWorkDispatchResult,
    DurableWorkOperation,
    apply_derivation_success,
    apply_derivation_terminal_failure,
    assert_exact_derivation_writes,
    derivation_target,
    operation_intent,
    run_work_handler,
    write_pending_derivations,
)

from .errors import (
    ErrorClass,
    ErrorCode,
    ErrorResult,
    OpResult,
    storage_failure,
)

from .inference_adapter import (
    create_inference_callbacks,
    target_ratios_of,
)

from .inference_types import (
    DEFAULT_GUARDS,
    DerivationGuards,
    InferenceConfig,
    ModelAssignment,
    ModelCall,
    ModelCallFailureKind,
    ModelCallInput,
    ModelCallResult,
    ResolvedDerivationGuards,
    ResolvedInferenceConfig,
    resolve_guards,
)

from .inspect import (
    HealthReport,
    InspectOverview,
    ViewContentsReport,
)

from .persist import (
    DbReadTransaction,
    DbWriteTransaction,
    PostCommitHook,
    create_db_read_transaction,
    create_db_write_transaction,
    create_post_commit_hook_set,
)

from .report import (
    RawReportRow,
    report_entry_from_row,
)

from .scheduler import (
    DrainDeps,
    DrainReport,
    Scheduler,
    SchedulerMode,
    ThreadDbOpener,
    create_scheduler,
    drain_open_db,
    peek_thread_id,
    run_drain,
)

from .storage import (
    CURRENT_THREAD_SCHEMA_VERSION,
    database_path_for,
    get_schema_version,
    open_database,
)

from .tool_result_rendering import (
    FALLBACK_TRUNCATION_LIMIT,
    truncate_for_fallback,
)

from .user_steer import (
    USER_STEER_IDEMPOTENCY_PREFIX,
    USER_STEER_PAYLOAD_VERSION,
    USER_STEER_RENDERING_LABEL,
    UserSteerPayload,
    user_steer_idempotency_key,
)

from .view import (
    Band,
    CompactReceipt,
    LlmRequestContext,
    LlmRequestContextMessage,
    LlmRequestContextPart,
    PreviewCompactOutcome,
    PreviewCompactResult,
    PruneReceipt,
    ResolvedViewConfig,
    SdkViewConfig,
    SessionAssistantMessage,
    SessionAssistantPart,
    SessionModelChangeEntry,
    SessionThinkingLevelChangeEntry,
    SessionThreadView,
    SessionThreadViewEntry,
    SessionThreadViewEntrySource,
    SessionThreadViewMessage,
    SessionToolResultMessage,
    SessionUserMessage,
    SessionUserSource,
    SessionUserSteerSource,
    StoredView,
    ViewCompactParams,
    ViewProfile,
    ViewProfileOverride,
    ViewStatus,
    VisibilityBudgets,
)

__all__ = [
    "Band",
    "CURRENT_THREAD_SCHEMA_VERSION",
    "CompactReceipt",
    "CompletionTx",
    "DEFAULT_GUARDS",
    "DETERMINISTIC_MARKERS",
    "DbReadTransaction",
    "DbWriteTransaction",
    "DependencyGap",
    "Derivation",
    "DerivationAttempt",
    "DerivationCompletionError",
    "DerivationGuards",
    "DerivationMetadata",
    "DerivationReportEntry",
    "DerivationState",
    "DeterministicOpName",
    "DrainDeps",
    "DrainReport",
    "DurableWorkDispatchResult",
    "DurableWorkDispatcher",
    "DurableWorkDispatcherMap",
    "DurableWorkOperation",
    "ErrorClass",
    "ErrorCode",
    "ErrorResult",
    "FALLBACK_TRUNCATION_LIMIT",
    "HandlerDerivationWrite",
    "HandlerOutcome",
    "HandlerRunContext",
    "HealthReport",
    "INFERENCE_CALLBACK_OPERATIONS",
    "InferenceCallbackName",
    "InferenceCallbacks",
    "InferenceConfig",
    "InferenceRequestMessage",
    "InferenceResult",
    "InspectOverview",
    "InstanceSeam",
    "LlmRequestContext",
    "LlmRequestContextMessage",
    "LlmRequestContextPart",
    "ModelAssignment",
    "ModelCall",
    "ModelCallFailureKind",
    "ModelCallInput",
    "ModelCallResult",
    "OpResult",
    "PostCommitHook",
    "PreviewCompactOutcome",
    "PreviewCompactResult",
    "ProviderProvenance",
    "PruneReceipt",
    "RawReportRow",
    "RenderingPart",
    "RenderingPartKind",
    "ResolvedDerivationGuards",
    "ResolvedInferenceConfig",
    "ResolvedSdkConfig",
    "ResolvedViewConfig",
    "Scheduler",
    "SchedulerMode",
    "SdkConfig",
    "SdkViewConfig",
    "SessionAssistantMessage",
    "SessionAssistantPart",
    "SessionModelChangeEntry",
    "SessionThinkingLevelChangeEntry",
    "SessionThreadView",
    "SessionThreadViewEntry",
    "SessionThreadViewEntrySource",
    "SessionThreadViewMessage",
    "SessionToolResultMessage",
    "SessionUserMessage",
    "SessionUserSource",
    "SessionUserSteerSource",
    "StoredView",
    "SubjectKind",
    "USER_STEER_IDEMPOTENCY_PREFIX",
    "USER_STEER_PAYLOAD_VERSION",
    "USER_STEER_RENDERING_LABEL",
    "UserSteerPayload",
    "ThreadDbOpener",
    "ToolOutcome",
    "ToolResultClassification",
    "ToolResultFacts",
    "ToolResultOperationClass",
    "ToolResultPromptMode",
    "ToolResultResponseShape",
    "ViewCompactParams",
    "ViewContentsReport",
    "ViewProfile",
    "ViewProfileOverride",
    "ViewStatus",
    "VisibilityBudgets",
    "WorkHandler",
    "apply_derivation_success",
    "apply_derivation_terminal_failure",
    "assert_exact_derivation_writes",
    "create_db_read_transaction",
    "create_db_write_transaction",
    "create_deterministic_inference_callbacks",
    "create_inference_callbacks",
    "create_post_commit_hook_set",
    "create_scheduler",
    "database_path_for",
    "derivation_target",
    "deterministic_digest",
    "deterministic_outcomes_suffix",
    "deterministic_text",
    "drain_open_db",
    "fire_thread_touch",
    "get_schema_version",
    "open_database",
    "operation_intent",
    "peek_thread_id",
    "report_entry_from_row",
    "resolve_guards",
    "resolve_instance_config",
    "resolve_instance_poke",
    "resolve_instance_view_config",
    "run_drain",
    "run_with_instance_seam",
    "run_with_thread_touch_suppressed",
    "run_work_handler",
    "safe_call",
    "set_scheduler_poke",
    "set_thread_touch",
    "storage_failure",
    "target_ratios_of",
    "truncate_for_fallback",
    "user_steer_idempotency_key",
    "write_pending_derivations",
]
