// Launcher-shim content and PATH logic behind install-shim.mjs, split out so
// content and path handling are unit-testable on every platform
// (packages/cc-lhc-native/test/setup-scripts.test.ts). Pure functions only.

export function shellQuote(value) {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

/** PowerShell single-quoted literal: only ' needs escaping (doubled); $, `` ` ``, etc. stay literal. */
export function psQuote(value) {
  return `'${value.replaceAll("'", "''")}'`;
}

/** POSIX launcher: bash shim with a missing-dist guard. */
export function posixShimContent(name, packageDir, distBin, repoRoot) {
  return (
    `#!/usr/bin/env bash\n` +
    `set -euo pipefail\n` +
    `DIST_BIN=${shellQuote(distBin)}\n` +
    `REPO_ROOT=${shellQuote(repoRoot)}\n` +
    `if [[ ! -f "$DIST_BIN" ]]; then\n` +
    `  echo "${name}: missing built launcher at $DIST_BIN" >&2\n` +
    `  echo "run: cd $REPO_ROOT && pnpm --config.verify-deps-before-run=false --filter ${packageDir} run build" >&2\n` +
    `  exit 1\n` +
    `fi\n` +
    `exec node "$DIST_BIN" "$@"\n`
  );
}

/**
 * Windows launcher, part 1: .cmd batch shim (runs from cmd.exe and PowerShell
 * alike, no execution-policy concerns). Its content is STABLE — it names only
 * the launcher name (a fixed token) and %~dp0, never a repo path — so an
 * arbitrary clone location can never be parsed as cmd source. All
 * machine-specific data lives JSON-encoded in the adjacent .launcher.js.
 */
export function windowsCmdShimContent(name) {
  if (!/^[A-Za-z0-9._-]+$/.test(name)) {
    throw new Error(`windows shim: unsafe launcher name ${JSON.stringify(name)}`);
  }
  return (
    [`@echo off`, `node "%~dp0${name}.launcher.js" %*`, `exit /b %ERRORLEVEL%`].join("\r\n") + "\r\n"
  );
}

/**
 * Windows launcher, part 2: the adjacent Node launcher the .cmd invokes.
 * Repo paths are embedded as JSON string literals (valid JS), interpreted
 * only by Node — cmd.exe never sees them. Mirrors the POSIX guard: refuse
 * with build guidance when dist is missing, otherwise run the dist under the
 * current Node with all arguments and propagate the exit code.
 */
export function windowsLauncherJsContent(name, packageDir, distBin, repoRoot) {
  return (
    `// Generated by install-shim.mjs — Windows launcher for ${name}.\n` +
    `"use strict";\n` +
    `const { spawnSync } = require("node:child_process");\n` +
    `const { existsSync } = require("node:fs");\n` +
    `const NAME = ${JSON.stringify(name)};\n` +
    `const PACKAGE_DIR = ${JSON.stringify(packageDir)};\n` +
    `const DIST_BIN = ${JSON.stringify(distBin)};\n` +
    `const REPO_ROOT = ${JSON.stringify(repoRoot)};\n` +
    `if (!existsSync(DIST_BIN)) {\n` +
    `  console.error(NAME + ": missing built launcher at " + DIST_BIN);\n` +
    `  console.error("run: cd " + REPO_ROOT + " && pnpm --config.verify-deps-before-run=false --filter " + PACKAGE_DIR + " run build");\n` +
    `  process.exit(1);\n` +
    `}\n` +
    `const result = spawnSync(process.execPath, [DIST_BIN, ...process.argv.slice(2)], { stdio: "inherit" });\n` +
    `if (result.error) {\n` +
    `  console.error(NAME + ": " + result.error.message);\n` +
    `  process.exit(1);\n` +
    `}\n` +
    `process.exit(result.status === null ? 1 : result.status);\n`
  );
}

function normalizePathEntry(entry, platform) {
  const trimmed = entry.replace(platform === "win32" ? /[\\/]+$/ : /\/+$/, "");
  return platform === "win32" ? trimmed.toLowerCase() : trimmed;
}

/**
 * Whether binDir is already on PATH. Windows comparison is case-insensitive
 * and tolerates trailing separators; POSIX is exact.
 */
export function binDirOnPath(binDir, pathValue, platform) {
  const separator = platform === "win32" ? ";" : ":";
  const want = normalizePathEntry(binDir, platform);
  return (pathValue ?? "")
    .split(separator)
    .filter((entry) => entry !== "")
    .some((entry) => normalizePathEntry(entry, platform) === want);
}

/** Actionable, platform-correct guidance for putting binDir on PATH. */
export function pathGuidance(binDir, platform) {
  if (platform === "win32") {
    // Single-quoted PowerShell literals: $ ` " and other metacharacters in
    // the directory stay literal; only embedded ' needs doubling.
    return [
      `NOTE: ${binDir} is not on PATH.`,
      `Add it persistently for your user (PowerShell):`,
      `  [Environment]::SetEnvironmentVariable('Path', [Environment]::GetEnvironmentVariable('Path', 'User') + ${psQuote(`;${binDir}`)}, 'User')`,
      `then open a new terminal. (Settings > System > About > Advanced system settings > Environment Variables works too.)`,
    ];
  }
  return [
    `NOTE: ${binDir} is not on PATH — add it in your shell profile, e.g.:`,
    `  export PATH="${binDir}:$PATH"`,
  ];
}
