export {
  createExactFileIdentityReader,
  type ExactFileIdentity,
  type ExactFileIdentityReader,
  exactFileIdentitiesEqual,
  type FileIdentityFailureCode,
  normalizeNativeFileResult,
  type ReadFileIdentityResult,
  readExactFileIdentity,
} from "./file-identity.js";
export {
  createExactIdentityReader,
  type ExactIdentityReader,
  type ExactProcessIdentity,
  exactIdentitiesEqual,
  type IdentityFailureCode,
  type IdentityPlatform,
  normalizeNativeResult,
  type ReadIdentityResult,
  readExactProcessIdentity,
  toPortableProcessIdentity,
} from "./identity.js";
export {
  ADDON_FUNCTION_EXPORTS,
  AddonArtifactMissingError,
  AddonContractError,
  type AddonSource,
  defaultPackageRoot,
  IDENTITY_ADDON_ENV,
  IDENTITY_CONTRACT_VERSION,
  type LoadedIdentityAddon,
  type LoaderSeams,
  loadIdentityAddon,
  type NativeIdentityAddon,
  type ResolvedAddonArtifact,
  resolveAddonArtifact,
  UnsupportedPlatformTargetError,
} from "./loader.js";
export {
  type ChildExitState,
  type ControlResult,
  createProcessControl,
  exactProcessControl,
  type FindChildHoldingFileResult,
  normalizeChildExitResult,
  normalizeControlResult,
  normalizeHolderResult,
  type ProcessControl,
  type ProcessControlFailure,
  type ProcessControlFailureCode,
  type ReadChildExitResult,
} from "./process-control.js";
export {
  missingReleaseBundleFiles,
  prebuiltArtifactRelativePath,
  RELEASE_BUNDLE_STATIC_FILES,
  type ReleaseBundleCheckOptions,
} from "./release-bundle.js";
export {
  isSupportedTarget,
  loadTargetsManifest,
  type PrebuildTarget,
  parseTargetsManifest,
  TARGETS_MANIFEST_FILENAME,
  type TargetsManifest,
  targetKey,
} from "./targets.js";
