import { randomBytes } from "node:crypto";
import { rmSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import { storageFailure, type ErrorResult, type OpResult } from "../../../shared/errors.js";
import {
  getSchemaVersion,
  openDatabase,
  runMigrations,
  type Migration,
} from "../../../shared/storage.js";
import { TOKEN_ESTIMATOR_ID } from "../../../tech-utils/token-counting/index.js";

// The one random id: its uniqueness scope is global across files and
// registries (design decision 7).
export function generateThreadId(): string {
  return `th_${randomBytes(8).toString("hex")}`;
}

// The thread-file schema as a versioned history, never rewritten in place:
// v1 is the Story 2 schema exactly as accepted (thread_metadata + event), and
// each later story appends a version. Existing files upgrade lazily through
// openThreadDatabase, so a file recorded under an earlier story is always
// usable by a later one (F-03-001).
//
// Creation-time metadata values are interpolated through buildThreadMigrations
// for new files only; existing files already hold their metadata row and the
// upgrade path never touches it.
function buildThreadMigrations(
  metadata?: { threadId: string; createdAt: string },
): Migration[] {
  const metadataInsert =
    metadata === undefined
      ? []
      : [
          // Interpolated values are all generated by us (hex id, ISO
          // timestamp, estimator constant) — never caller input.
          `INSERT INTO thread_metadata (id, thread_id, created_at, token_estimator)
           VALUES (1, '${metadata.threadId}', '${metadata.createdAt}', '${TOKEN_ESTIMATOR_ID}');`,
        ];
  return [
    {
      version: 1,
      statements: [
        `CREATE TABLE thread_metadata (
          id INTEGER PRIMARY KEY CHECK (id = 1),
          thread_id TEXT NOT NULL,
          created_at TEXT NOT NULL,
          token_estimator TEXT NOT NULL
        );`,
        ...metadataInsert,
        `CREATE TABLE event (
          event_order INTEGER PRIMARY KEY,
          event_kind TEXT NOT NULL,
          idempotency_key TEXT NOT NULL UNIQUE,
          actor TEXT NOT NULL,
          harness TEXT NOT NULL,
          payload TEXT NOT NULL,
          recorded_at TEXT NOT NULL
        );`,
      ],
    },
    {
      version: 2, // Story 3: message projection
      statements: [
        `CREATE TABLE message (
          message_id TEXT PRIMARY KEY,
          source_event_order INTEGER NOT NULL UNIQUE REFERENCES event(event_order),
          kind TEXT NOT NULL,
          token_estimate INTEGER NOT NULL,
          actor TEXT NOT NULL,
          harness TEXT NOT NULL,
          turn_id TEXT
        );`,
        `CREATE TABLE message_block (
          message_id TEXT NOT NULL REFERENCES message(message_id),
          block_index INTEGER NOT NULL,
          block_type TEXT NOT NULL,
          content TEXT NOT NULL,
          PRIMARY KEY (message_id, block_index)
        );`,
      ],
    },
    {
      version: 3, // Story 4: turn state machine
      statements: [
        `CREATE TABLE turns (
          turn_id TEXT PRIMARY KEY,
          turn_order INTEGER NOT NULL UNIQUE,
          status TEXT NOT NULL CHECK (status IN ('open', 'closed')),
          opened_at_event_order INTEGER NOT NULL,
          closed_at_event_order INTEGER
        );`,
      ],
    },
    {
      version: 4, // Story 5: derivation work queueing
      statements: [
        // Work items live in the thread file and commit with the batch —
        // not a separate database, not a separate transaction. status is
        // unconstrained TEXT: this epic only ever writes 'queued'; the
        // claim/lease statuses are Epic 02's to add.
        `CREATE TABLE work_item (
          work_item_id TEXT PRIMARY KEY,
          owner TEXT NOT NULL,
          kind TEXT NOT NULL,
          source_ref TEXT NOT NULL,
          status TEXT NOT NULL,
          queued_at TEXT NOT NULL
        );`,
      ],
    },
  ];
}

function notAThreadFile(filePath: string, detail: string): { ok: false; error: ErrorResult } {
  return {
    ok: false,
    error: {
      errorClass: "caller_error",
      code: "thread_not_found",
      reason: `file at ${filePath} exists but is not an lhc thread file (${detail})`,
    },
  };
}

function errorDetail(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause);
}

// Identity check before any migration runs, on a read-only handle so an
// invalid file cannot be mutated by the probe itself (F-03-002): a thread
// file always carries schema version >= 1 and the thread_metadata singleton
// row that creation wrote transactionally. Anything else — an empty
// database, an unrelated SQLite file, a non-database file — is rejected as a
// caller error, never adopted.
function validateThreadFile(filePath: string): { ok: true } | { ok: false; error: ErrorResult } {
  let db: DatabaseSync | undefined;
  try {
    db = new DatabaseSync(filePath, { readOnly: true });
    if (getSchemaVersion(db) < 1) {
      return notAThreadFile(filePath, "no lhc schema version");
    }
    const table = db
      .prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'thread_metadata'")
      .get();
    if (table === undefined) {
      return notAThreadFile(filePath, "no thread_metadata table");
    }
    const row = db.prepare("SELECT thread_id FROM thread_metadata WHERE id = 1").get();
    if (row === undefined) {
      return notAThreadFile(filePath, "no thread metadata row");
    }
    return { ok: true };
  } catch (cause) {
    const detail = errorDetail(cause);
    // SQLite refusing the file as a database is an identity failure, not an
    // environment failure; everything else stays a system error.
    if (detail.includes("not a database")) {
      return notAThreadFile(filePath, detail);
    }
    return storageFailure(`could not inspect thread file: ${detail}`);
  } finally {
    db?.close();
  }
}

// Opens a thread file and brings its schema to the current version before
// returning the handle. Every SDK operation on an existing thread file goes
// through here, so a pre-Story-3 file gains the message tables on its first
// open by newer code — but only after the file proves it is a thread file;
// migration never creates lhc schema on an arbitrary existing file. Each
// migration runs in its own transaction (storage helper), completing before
// any caller transaction begins.
export function openThreadDatabase(filePath: string): OpResult<DatabaseSync> {
  const valid = validateThreadFile(filePath);
  if (!valid.ok) return valid;
  let db: DatabaseSync;
  try {
    db = openDatabase(filePath);
  } catch (cause) {
    return storageFailure(`could not open thread file: ${errorDetail(cause)}`);
  }
  try {
    runMigrations(db, buildThreadMigrations());
  } catch (cause) {
    db.close();
    return storageFailure(`thread schema migration failed: ${errorDetail(cause)}`);
  }
  return { ok: true, value: db };
}

// Schema v1 plus the metadata row land in one migration transaction, so the
// file either has its full schema and metadata row or creation fails whole.
export function createThreadFile(
  filePath: string,
  threadId: string,
  createdAt: string,
): void {
  const db = openDatabase(filePath);
  try {
    runMigrations(db, buildThreadMigrations({ threadId, createdAt }));
  } finally {
    db.close();
  }
}

// Compensation: removes the thread file and its WAL companions. Used when the
// registry insert fails after file creation (no registry row without its
// file) and when file creation itself fails partway.
export function deleteThreadFile(filePath: string): void {
  for (const suffix of ["", "-wal", "-shm"]) {
    rmSync(`${filePath}${suffix}`, { force: true });
  }
}
